# Generated by Django 5.1.6 on 2025-03-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pattern_bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimtime',
            name='time',
            field=models.TimeField(),
        ),
    ]
