# Generated by Django 5.1.6 on 2025-03-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pattern_bank', '0002_alter_dimtime_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimdate',
            name='dayOfMonth',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='dimdate',
            name='dayOfWeek',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='dimdate',
            name='dayOfYear',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='dimdate',
            name='isWorkingDay',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='dimdate',
            name='monthId',
            field=models.SmallIntegerField(),
        ),
    ]
